import Head from 'next/head'
import { PropsWithChildren } from 'react'

export const ViewportWrapper = ({ title, children }: PropsWithChildren & { title: string }) => {

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        {children}
      </main>
    </>
  )
}
